postgresql:
  image: katbara/postgresql
  environment:
    - POSTGRESQL_DB=personnel_management
    - POSTGRESQL_USER=personnel_management
    - POSTGRESQL_PASSWORD=password
  volumes:
    - ~/dockerfiles/personnel_management/postgresql:/var/lib/postgresql
  ports:
    - "5432:5432"


djangobase:
  image: katbara/django
  environment:
    - PYTHONIOENCODING=utf8
    - DATABASE_HOST=postgresql
    - DJANGO_SETTINGS_MODULE=personnel_management.settings.local
    - C_FORCE_ROOT=true  # Allows celery to run as root.
  working_dir: /personnel_management
  volumes:
    - .:/personnel_management
    - ~/dockerfiles/personnel_management/python:/usr/local/lib/python3.6
    - ~/dockerfiles/personnel_management/bin:/usr/local/bin


django:
  extends:
    service: djangobase
  command: bash -c "sleep 3 && python3.6 manage.py runserver_plus 0.0.0.0:80"
  ports:
    - "80:80"
  links:
    - postgresql
